// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MacroScript
{
    internal sealed partial class Vsix
    {
        public const string Id = "MacroScript.105d5efd-8a92-44a3-bf70-c94e2487a28b";
        public const string Name = "MacroScript";
        public const string Description = @"A scripting module that aids in coding by letting the developer code scripts that extend visual studio's functionality.";
        public const string Language = "en-US";
        public const string Version = "4.0";
        public const string Author = "Silver Dimond";
        public const string Tags = "";
    }
}
