// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MacroScript
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MacroScriptString = "73403a68-6dc3-4748-b9e3-b57e81c1814d";
        public static Guid MacroScript = new Guid(MacroScriptString);

        public const string guidMacroScriptPackageCmdSetString = "a6fb8673-00d0-4a80-8967-8a1d5c970b27";
        public static Guid guidMacroScriptPackageCmdSet = new Guid(guidMacroScriptPackageCmdSetString);

        public const string guidImagesString = "60e9de1b-580e-4910-af6f-bc04fc44a620";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int cmdidMainToolWindoCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}